# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend - Sistrel / CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest # Qual sistema operacional vai rodar

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow  
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
       
    - name: Install dependencies
      run: yarn --frozen-lockfile
    
    - name: Run all tests
      run: yarn test:e2e

    - shell: bash
      name: Create SSH deployment key
      env: 
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: ./scripts/deploy.sh

    - name: Deployment
      run: git remote add umbler ssh://git@kamino.deploy.umbler.com:9922/j5r0qg5k/backend-sistrel-com-br.git && git push umbler master